<template>
<p>
Right now I can look out my window and see 6 different televisions in 6 different windows. In 2 of them I can also see the people watching the television. They are totally limp. Their faces have that terrifying emptiness not found in sleep or death, but vegetation: the lobotomized half-dead state where the heart is still beating and the eyes are open but the mind isn't really aware of anything at all. 
Have you ever looked at someone who was watching TV and thought: "Damn, what a hero. I want to be like that."
Behind the condo across the street, in the background before DTSF and the Benioff Tower, is the Benioff Children's Hospital. I can see the 20% or so of windows that are still lit, distant figures in scrubs folding blankets and arranging equipment around beds which I assume hold sick kids, which I cannot see. In the dark windows I can still see the kelly green LCD sentinels declaring O2 and BPM to their sleeping bodies.
<a href="https://jsomers.net/DFW_TV.pdf" target="_blank">David Foster Wallace wrote an essay in the early 90s</a> in which he states: "Statisticians report that television is watched over six hours a day in the average American household." This was well before people began watching TV in their hand as they walk down the street, as I see both Zs and Boomers doing regularly. Add in the 30-second bytes you spend drooling at GIFs in the grocery line or when you're on the pisser, and suddenly we are literally staring at this thing all the time. <a href="https://www.youtube.com/watch?v=s0TvZRcwz4I" target="_blank">I had a girlfriend who would dream about the television</a> shows she was watching, so we might as well count those hours too. 
This all bothered me before COVID hit, and the economy crashed, but I didn't want to throw shade at people just to feel superior. But things have changed, hard and fast. I don't need to go into detail here beacuse everyone is already personally aware, in myriad ways. My point is maybe we need to reconsider the opportunity cost of staring at fluffy happy things, or even "informative, educational news" etc. etc. 
The rebuttal here usually makes heavy use of the neologism: 'self-care', as in care about yourself, and only yourself, because "you deserve it." You might even lose your shit and overdose on Klonopin or shoot up a movie theater if you don't 'self-care', so it's very, very important that we all #treatyoself, right now, #erryday. The advertising-venture-capital complex that fuels most US job growth right now is heavily dependent on this narrative. You can't self-care without buying something (except with meditation which by definition you must never pay for: #ajahn_geoff <a href="https://www.dhammatalks.org/mp3_index_current.html" target="_blank">dhammatalks.org</a>)
We've bought this lie (#literally) and it's killing us (#<a href="https://www.cdc.gov/mmwr/volumes/69/wr/mm6932a1.htm" target="_blank">literally</a>). People are attending protests, but posting about those protests on social media and thus are generating ad-revenue for rich, white, first-wave tech owners (e.g. Gates, Jobs, Bezos, Zuckerberg, and all the other heirs of Gordon Macklin / NASDAQ / Automated Trading / Aqusition-based Wealth). Then they go home and watch Netflix-produced documentaries about these issues on their mass-market Apple/Samsung devices. Why doesn't anything ever change?
I have a solution: everybody needs to learn code, right now. It's no more difficult than picking up any other craft like knitting or carpentry. You learn the tools, the techniques, you commit to screwing up until you're good. The huge bonus w/ code: once you have a computer and The Internet, the cost of materials is essentially $0. 
If everybody knows code like everybody knows how to read, we can build open-source platforms that can be configured and maintained locally, by the people actually using them. We can make art and journalism and cooking recipes like we've never imagined because we'll have new tools that we've invented. We can do this instead of watching television!
</p>
</template>